"""
extract_suspected_ftp.py

This script extracts suspected False True Positives (FTP) from a matching_files_X.csv
generated by the frame probability analysis.

It:
- Parses the CSV to get a list of audio files.
- Copies the corresponding audio files (YTID-based) to a destination folder.
- Avoids duplicates across multiple runs.
- Creates a CSV log of all copied files.

Default input:
--------------
If no --csv argument is passed, the default is:
    outputs/frame_distributions/matching_files_3.csv

Output:
-------
- Copies files to: files/AudioSet_EV_Strong_Suspected_FTP/
- Saves list of copied files to: files/AudioSet_EV_Strong_Suspected_FTP/filelist.csv

Usage:
------
$ python extract_suspected_ftp.py
$ python extract_suspected_ftp.py --csv outputs/frame_distributions/matching_files_2.csv

Dependencies:
-------------
- Python 3.7+
"""

import pandas as pd
from pathlib import Path
import shutil
import argparse

# Constants
DEFAULT_CSV_PATH = "outputs/frame_distributions/matching_files_up_to_0.csv"
SRC_DIR = Path("files/AudioSet_EV_Positives")
DST_DIR = Path("files/AudioSet_EV_Strong_Suspected_FTP")
DST_DIR.mkdir(parents=True, exist_ok=True)

# Parse arguments
parser = argparse.ArgumentParser(description="Extract audio files matching potential FTPs.")
parser.add_argument("--csv", type=str, default=DEFAULT_CSV_PATH, help="Path to matching_files_X.csv")
args = parser.parse_args()
input_csv = Path(args.csv)

# Load matching file list
if not input_csv.exists():
    raise FileNotFoundError(f"Input CSV file not found: {input_csv}")

df = pd.read_csv(input_csv)
copied_files = []

# Copy matching audio files
for filename in df["file"]:
    ytid = filename.split("_")[0]  # Extract YTID
    candidates = list(SRC_DIR.glob(f"{ytid}_*.wav"))
    
    if not candidates:
        print(f"No audio file found for: {ytid} in {SRC_DIR}")
        continue

    for src_file in candidates:
        dst_file = DST_DIR / src_file.name
        if not dst_file.exists():
            shutil.copy(src_file, dst_file)
            copied_files.append(dst_file.name)


# Save file list
filelist_path = DST_DIR / "filelist.csv"
pd.DataFrame({"filename": copied_files}).to_csv(filelist_path, index=False)

print(f"Copied {len(copied_files)} files to {DST_DIR}")
print(f"File list saved to: {filelist_path}")
