# frame_probability_distribution.py

"""
This script analyzes the distribution of high-confidence inference frames across multiple experiment runs.

It processes the `inference_metrics` CSV files generated by the real-time audio inference pipeline and:
- Counts how many frames in each audio file exceed a given probability threshold.
- Aggregates and groups the results by checkpoint.
- Outputs histograms and CSVs representing the number of files with N frames over the threshold.
- Additionally, saves a CSV file listing all filenames with up to N_FRAMES_MATCH over the threshold.

The script supports multiple experiments, each corresponding to a folder under `outputs/`, such as:
    - outputs/constant_frame
    - outputs/variable_frame_ot05_aw02
    - outputs/variable_frame_ot05_aw04

Usage:
------
Run the script from the project root:
    $ python frame_probability_distribution.py

Outputs:
--------
- PNG and SVG histograms: saved under `outputs/frame_distributions/`
- CSV summaries for each experiment
- CSV with files matching N_FRAMES_MATCH: saved under `outputs/frame_distributions/matching_files_{N_FRAMES_MATCH}.csv`

Adjustable Parameters:
----------------------
- `PROB_THRESHOLD`: The probability threshold used to count valid frames
- `N_FRAMES_MATCH`: The number of frames required for match tracking
- `EXPERIMENTS`: Mapping of experiment labels to output directories

Dependencies:
-------------
- pandas
- matplotlib
- Python 3.7+
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# Parameters
EXPERIMENTS = {
    "constant_frame": "outputs/constant_frame",
    "variable_frame_ot05_aw02": "outputs/variable_frame_ot05_aw02",
    "variable_frame_ot05_aw04": "outputs/variable_frame_ot05_aw04",
}
SUBFOLDER = "inference_metrics"
PROB_THRESHOLD = 0.5  # adjust as needed
N_FRAMES_MATCH = 2
PLOT_DIR = Path("outputs/frame_distributions")
PLOT_DIR.mkdir(parents=True, exist_ok=True)

matching_files = []

def count_frames_above_threshold(csv_path, threshold):
    df = pd.read_csv(csv_path)
    return (df["Inference Result"] >= threshold).sum()

def compute_distribution(folder_path):
    folder = Path(folder_path)
    count_dict = {}
    for checkpoint_dir in folder.iterdir():
        if not checkpoint_dir.is_dir():
            continue
        checkpoint_name = checkpoint_dir.name
        dist = {}
        for csv_file in (checkpoint_dir / SUBFOLDER).glob("*.csv"):
            count = count_frames_above_threshold(csv_file, PROB_THRESHOLD)
            dist[count] = dist.get(count, 0) + 1
            if count <= N_FRAMES_MATCH:
                matching_files.append({
                    "experiment": folder.name,
                    "checkpoint": checkpoint_name,
                    "file": csv_file.name,
                    "matched_frames": count
                })
        count_dict[checkpoint_name] = dist
    return count_dict

def plot_distribution(distribution, title, filename):
    plt.figure(figsize=(10, 6))
    total_series = len(distribution)
    width = 0.25
    offsets = [(i - total_series/2) * width for i in range(total_series)]
    all_x = sorted({x for dist in distribution.values() for x in dist})

    # Predefine grayscale colors and hatching styles
    gray_levels = ["0.2", "0.5", "0.8"]  # dark, medium, light gray
    hatches = ["///", "\\\\\\", "xxx"]
    plt.rcParams.update({
        'font.size': 16,           # Base font size
        'axes.titlesize': 16,      # Title
        'axes.labelsize': 16,      # X and Y labels
        'xtick.labelsize': 12,     # Tick labels
        'ytick.labelsize': 12,
        'legend.fontsize': 16,
        })

    for idx, (checkpoint, counts) in enumerate(distribution.items()):
        y = [counts.get(k, 0) for k in all_x]
        x_pos = [x + offsets[idx] for x in range(len(all_x))]
        plt.bar(x_pos, y,
                width=width,
                alpha=1.0,
                label=checkpoint,
                color=gray_levels[idx % len(gray_levels)],
                edgecolor="black",
                linewidth=0.6,)
                #hatch=hatches[idx % len(hatches)])

    #plt.title(title)
    plt.xlabel(f"# of Frames with prob. >= {PROB_THRESHOLD}")
    plt.ylabel("Number of Audio Files")
    plt.xticks(ticks=range(len(all_x)), labels=all_x)
    plt.legend()
    plt.grid(True, linestyle='--', linewidth=0.5)
    plt.tight_layout()
    plt.savefig(PLOT_DIR / f"{filename}.png", dpi=600)
    plt.savefig(PLOT_DIR / f"{filename}.svg")
    plt.close()

def save_distribution_csv(distribution, filename):
    all_keys = sorted({k for dist in distribution.values() for k in dist})
    df = pd.DataFrame(index=all_keys)
    for checkpoint, dist in distribution.items():
        df[checkpoint] = pd.Series(dist)
    df = df.fillna(0).astype(int)
    df.index.name = f"# of Frames ? {PROB_THRESHOLD}"
    df.to_csv(PLOT_DIR / f"{filename}.csv")

# Main
for experiment_name, folder in EXPERIMENTS.items():
    print(f"Processing experiment: {experiment_name}")
    distribution = compute_distribution(folder)
    plot_distribution(distribution,
                      title=f"Frame Count Distribution ({experiment_name})",
                      filename=experiment_name)
    save_distribution_csv(distribution, filename=experiment_name)

# Save matched files CSV
if matching_files:
    pd.DataFrame(matching_files).to_csv(
        PLOT_DIR / f"matching_files_up_to_{N_FRAMES_MATCH}.csv",
        index=False
    )

print(f"\nDone. Results saved in: {PLOT_DIR.resolve()}")
